### ISSUE TITLE
Search isn't working?

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#12]
I'm not sure why but this is not working. https://techworkersco.github.io/search/

It should open up a custom duckduckgo search.

The implementation is pretty much identical to SwiftWeekly, which works fine:
https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_includes/search_box.html

Maybe it's some indexing bug/problem?

**Comment by jessesquires** [comment]
Ok, so I did the whole site verification for google in 5a1b4e6a9fd488f40229b7fee21f2fe763c33697.

And now [search is working there](https://www.google.com/search?newwindow=1&hl=en&ei=V3OXXuyVGJOU-gSUz6GIBw&q=unite+here+site%3Ahttps%3A%2F%2Ftechworkersco.github.io&oq=unite+here+site%3Ahttps%3A%2F%2Ftechworkersco.github.io&gs_lcp=CgZwc3ktYWIQA0oJCBcSBTEyLTYxSgkIGBIFMTItMTBQhKUBWJWuAWCXuwFoAHAAeACAAUWIAdoEkgECMTCYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwisneGdp-voAhUTip4KHZRnCHEQ4dUDCAs&uact=5). So we're indexed by google. 👌 

However, [duckduckgo seach](https://duckduckgo.com/?q=unite+here+site%3Atechworkersco.github.io&t=osx&ia=web) still produces no results. 😭 I do not think they have a similar "site verification" thing.

@anaulin any thoughts here? (seems like this should have been indexed by now....)

**Comment by anaulin** [comment]
I've never really worked with DDG, so this is all based on a little bit of research I just did, and not on any direct experience. So apply the appropriate pinch of salt. 🧂 

It seems DuckDuckGo gets some (most?) of their search results from Bing: 
> DuckDuckGo gets its results from over four hundred sources. These include hundreds of vertical sources delivering niche Instant Answers, DuckDuckBot (our crawler) and crowd-sourced sites (like Wikipedia, stored in our answer indexes). We also of course have more traditional links in the search results, which we also source from multiple partners, though most commonly from Bing (and none from Google).

(source: https://help.duckduckgo.com/duckduckgo-help-pages/results/sources/)

I checked and the newsletter site is not being indexed by Bing yet (see e.g. https://www.bing.com/search?q=unite%20site%3Atechworkersco.github.io).

So my best guess is that we should submit the site for indexing to Bing, which apparently involves using their Webmaster Tools (https://www.bing.com/toolbox/webmaster). Can you do that, @jessesquires , so that one of us has access to both the Bing and Google Webmaster consoles for the site?

**Comment by jessesquires** [comment]
Ahhh. Thank youuu @anaulin 🙌 

Yes, I'll do this.

**Comment by jessesquires** [comment]
d9c62f9314b1ab4bb8caba3b5dee9dd9af61c390

**Comment by anaulin** [comment]
Great, thanks for that. And now we wait. ⏳

**Comment by jessesquires** [comment]
Goddamn. It looks like DDG and Bing **still** are not working.

We just implemented the custom domain (#18). Maybe that will help?

**Comment by anaulin** [comment]
@jessesquires I am not sure how the URL submission stuff works once we have a new domain. Do we need to re-submit to both Google and Bing? Or will they follow the redirects?

I also see in my Bing Webmaster Tools the option to "import" a site from the Google Search Console (on the right side of the UI at https://www.bing.com/webmaster/home/mysites):
![Screen Shot 2020-04-27 at 4 25 35 PM](https://user-images.githubusercontent.com/6729309/80430556-c4249500-88a3-11ea-9917-3243089eaf97.png)

Maybe submitting to Bing via this "import from Google" would make things faster? I'm grasping at straws here, sadly...

**Comment by jessesquires** [comment]
Hm.. I'm assuming they follow redirects. I can check.

**Comment by jessesquires** [comment]
Ok. Updated both.

🤷 🤷 🤷 🤷

**Comment by anaulin** [comment]
OMG @jessesquires you did it!

![Screen Shot 2020-05-02 at 8 19 42 AM](https://user-images.githubusercontent.com/6729309/80868191-be390600-8c4d-11ea-8890-376a56822082.png)

**Comment by jessesquires** [comment]
FUCK YES. 🎉 

I tried myself and it worked for me too!

closing.
