### ISSUE TITLE
Consider crediting old TWC Newsletter crew on vol 1 issues

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#13]
Check in with the old crew, credit them as desired / appropriate (or not credit them, if any want to stay anonymous).

Maybe have it someone at least in the README or in the site itself clarified that a different group created and published those original issues.

**Comment by stationaery** [comment]
Doubt the old crew want to be named/identified individually but yes we
should at least specific that this is a revival with new folks (I tried my
hand at some copy to that effect)

**Comment by jessesquires** [comment]
> Doubt the old crew want to be named/identified individually

I agree.

> Maybe have it someone at least in the README

I think the README works good. 👌

**Comment by jessesquires** [comment]
Closing this as resolved with our new about page.
