### ISSUE TITLE
Implement auto-merging on publish days

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#170]
New GitHub action that runs every Friday morning.

If PR has `auto-merge on friday morning` label, then merge at 9am.

**Comment by stationaery** [comment]
I like how we discussed doing what brings us joy individually, and now
these improvements you’re making @jessesquires look like they’ll bring joy
to all of us 😊😊😊😊😊😊

**Comment by jessesquires** [comment]
Ok, this is done! 🎉 

### How it works

The bot will begin checking for pull requests at `08:30am PST` or `09:30am PDT` every Friday. (The time discrepancy is because of daylight savings, and we must provide a single time in UTC. So this is the best compromise to meet our 11am mailchimp deadline and still have room for last-minute fixes/edits.)

It will check every 30 min for 3 hours.

The bot will merge the PR **if and only if**:
- the PR has the `auto-publish` label
- all status checks are green ✅ 
- PR has been approved ✅ 

---

Couldn't test via pull request so pushed directly at aa860696c5b8c8842372f33de27849f1049eb23c. 

Tested using #175 dry runs:
https://github.com/techworkersco/techworkersco.github.io/actions?query=workflow%3A%22Publish+Newsletter%22

**Comment by jessesquires** [comment]
At least, this is how it **should** work. We'll see next Friday. 😅
