### ISSUE TITLE
Vol. 3 appearing in the archive

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#182]
Right now, issues in Volume 3 do not seem to appear in https://news.techworkerscoalition.org/archive/ 🤔

**Comment by jessesquires** [comment]
@stationaery you made https://github.com/techworkersco/techworkersco.github.io/pull/179 for 2020, not 2021

**Comment by jessesquires** [comment]
i'm fixing now

**Comment by jessesquires** [comment]
partially my fault. i will add checks to the script to prevent creating issue in the past
