### ISSUE TITLE
[Infra] comment on PR with preview of issue

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#183]
This would be nice to have, but will require some work...

On CI:

1. Install [webkit2png](https://paulhammond.org/webkit2png), `brew install webkit2png`
2. serve the site locally in the background, `bundle exec jekyll serve &`
3. capture the screenshot `webkit2png --fullsize --width=1000 --filename=preview http://127.0.0.1:4000`
4. file will be saved to `preview-full.png`
5. foreground and kill the local server
6. . find a way (probably via the GitHub API) to post a comment on the PR with the image

We could trigger this action on a PR by adding a new label, `comment with preview` or something like that.

**Comment by shushugah** [comment]
I think the simpler solution would be to create a Netlify preview, which you can share links with people

**Comment by jessesquires** [comment]
closing as "done" via the netlify solution
