### ISSUE TITLE
Update list of twitter accounts

### ISSUE THREAD

**Issue by shushugah** [techworkersco/techworkersco.github.io#20]
Some twitter accounts, like @TechWorkersBER are missing. For a full list of TWC affiliated social media accounts, see here https://docs.google.com/spreadsheets/d/1vuEDunlJ4IkaiW_AMcOtENWFI-VBGsYW40eBGRryNBA/edit#gid=0

**Comment by stationaery** [comment]
Thanks! That helps a lot. We’re a couple weeks away from getting our README
and other materials together. Would be good to chat elsewhere about all
other infrastructure and ownership & governance.
