### ISSUE TITLE
Figure out where does https://techworkerscoalition.org/subscribe/ entries go to

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#21]
In this form, there is an option to "subscribe to newsletter". Which newsletter does this go to? 

Update it to wherever the right subscription mechanism will be for the revived newsletter.

**Comment by jessesquires** [comment]
Also relevant: #19

I was just going to submit a PR to direct to our new newsletter, once we have subscription setup and working.

**Comment by anaulin** [comment]
Yeah, updating that directly sounds great, if that's possible.

**Comment by jessesquires** [comment]
closing this in favor of #19
