### ISSUE TITLE
Header image appears blown up in MailChimp email

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#31]
This is how Issue 1 looks in the email I got from MailChimp:

![Screen Shot 2020-05-01 at 2 40 25 PM](https://user-images.githubusercontent.com/6729309/80843703-d3fceb80-8bb9-11ea-8f51-9ddf16038136.png)

That image is at more than 100% scale. Not sure why.

It would be good to figure out how to make the images display fine in the emails (maybe they need a width tag or something?).

**Comment by dellsystem** [comment]
closed with 12297e86fb25f7abfd4760e5934156a0014de5ab!

**Comment by jessesquires** [comment]
I also enabled this setting, which I think might fix things in the future?

<img width="680" alt="Screen Shot 2020-05-02 at 7 30 16 PM" src="https://user-images.githubusercontent.com/2301114/80897207-6fba5480-8cab-11ea-966c-7afdcdaed5b8.png">

**Comment by anaulin** [comment]
OMG, that looks exactly like the setting we were looking for. Where is that set?

**Comment by jessesquires** [comment]
If go through the edit campaign process, it's near the beginning, where you choose the schedule
