### ISSUE TITLE
DuckDuckGoNoGo

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#331]
Interesting hiccup... the DDG site search setup seems to be broken; searching any keyword at all turns up zero results.

**Comment by jessesquires** [comment]
@stationaery This is an ongoing issue for many different sites, unfortunately.

See:
- https://www.jessesquires.com/blog/2022/03/25/my-website-disappeared-from-bing-and-duckduckgo/
- https://www.jessesquires.com/blog/2022/04/17/duckduckgo-removing-other-sites/

**Comment by stationaery** [comment]
Looks like this got resolved!...?

**Comment by jessesquires** [comment]
@stationaery Yes, I think so. (As in DDG and Bing fixed their shit.)
