### ISSUE TITLE
Import missing newsletter issues

### ISSUE THREAD

**Issue by dellsystem** [techworkersco/techworkersco.github.io#35]
All of 2019 is missing

**Comment by anaulin** [comment]
The cobbled-together script I used for the initial import has a method that will try to scrape up an issue, given a URL and a bit of metadata:
```ruby
# Imports the issue at the given URL with the provided metadata.
# @params [Hash] issue A hash with title, date and url keys. Represents the issue to import.
def import_issue(issue)
```
(https://github.com/techworkersco/techworkersco.github.io/blob/master/scripts/import_legacy_issues.rb)

We could start by assembling a list of `{url, date, title}` objects for the missing issues, and then run them through that method. That at least will generate the markdown files for each issue, and attempt to download header images and such. Then we can go over the results of that and fix up whatever was not scraped right.

Alternatively this can all be done by hand, of course. It's a bunch of work either way. Let me know if/what help you'd like with this.

**Comment by dellsystem** [comment]
this is going well! i'll have a PR soon with all the remaining issues (hopefully tonight)

**Comment by jessesquires** [comment]
@dellsystem whoa awesome! 👏
