### ISSUE TITLE
Update MailChimp templates to include "email preview" text

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#37]
The issue frontmatter now has a `preview` item, which is shown in e.g. the Twitter card "description" text. We would like to have this preview text also be what shows up in the MailChimp email previews.

This work will require figuring out how to pull out this "preview" text from the RSS feed, and pulling it into MailChimps "email preview" template.

**Comment by jessesquires** [comment]
Did we vote on not just using the excerpt text for this?

**Comment by jessesquires** [comment]
Oh, is this a duplicate of #34?

**Comment by anaulin** [comment]
Yep, this is a duplicate of #34 . I missed that it was already filed, sry.
