### ISSUE TITLE
New year, new volume

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#373]
Hi @jessesquires - we took a couple months off but we're back with a batch of new stories. Can you turn the newsletter volume dial up from 4 to 5?

**Comment by jessesquires** [comment]
done 👍🏼 

If you're curious, all you need to do is update the default volume number here:
https://github.com/techworkersco/techworkersco.github.io/blob/master/.github/workflows/new-issue-pr.yml#L12

😄

**Comment by stationaery** [comment]
> If you're curious

I was! Thanks for both the update and the info 😊😊

**Comment by jessesquires** [comment]
no problem! 😄
