### ISSUE TITLE
Latest issue not showing up on the site

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#375]
Looks like https://github.com/techworkersco/techworkersco.github.io/pull/374 is done... but the issue isn't appearing on https://news.techworkerscoalition.org/ ?

Maybe this is a Netlifly issue?

**Comment by jessesquires** [comment]
> Maybe this is a Netlifly issue?

No. That's separate.

Taking a look now.

**Comment by jessesquires** [comment]
Hm. It appears to be an issue with GitHub Pages hosting...

I checked out everything locally and everything looks good.

The permalink should be: https://news.techworkerscoalition.org/2023/02/28/issue-1/

All checks, builds, and deployments succeeded: https://github.com/techworkersco/techworkersco.github.io/actions/workflows/pages/pages-build-deployment

<img width="880" alt="Screenshot 2023-02-28 at 10 35 33 AM" src="https://user-images.githubusercontent.com/2301114/221947643-0ac3f4f7-e173-411e-9ff9-3a20d7a3fdbb.png">

**Comment by jessesquires** [comment]
GitHub status does not currently indicate any issues with Pages deployments...

https://www.githubstatus.com

**Comment by jessesquires** [comment]
Just pushed an empty commit to trigger a rebuild:
https://github.com/techworkersco/techworkersco.github.io/commit/a79a84ea1890bd7510e0b8bebf820a999b41cbcc

Doubt this will work though...

**Comment by stationaery** [comment]
Looks like it's live now- https://news.techworkerscoalition.org/2023/02/28/issue-1/

**Comment by shushugah** [comment]
I added `bundle exec` prefix which initially didn’t fix it, but redeploying without cache enabled worked. So a not 100% certain what the issue was.

**Comment by jessesquires** [comment]
nice! 🥳
