### ISSUE TITLE
"Import" legacy newsletter issues?

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#5]
The old newsletter was only distributed manually via MailChimp. 

Those legacy issue live in this obscure archive on mailchimp's servers:
https://us11.campaign-archive.com/home/?u=194e57c175176cfd13007a197&id=7cb85d276a

It would be cool (but very tedious) to "import" those old issues to this new site. There are only about 20 issues, so it's not too bad.

Then, this site could contain everything we've done with the newsletter. 

And it would be searchable.

**Comment by jessesquires** [comment]
Maybe once we start publishing again, I can ping the Slack channel and see if anyone is interested in volunteering to do this? Not much else to do while we "shelter-in-place" 😄

**Comment by dellsystem** [comment]
[assigning this to Ana who volunteered to write a script for this]

**Comment by anaulin** [comment]
I'll aim to have a PR up to include the Volume 1 issues of the newsletter by April 14th.

**Comment by jessesquires** [comment]
jekyll frontmatter for the legacy issues:

```jekyll
---
layout: post
title: ! 'Issue #N'
categories: [volume1]
---
```

**Comment by anaulin** [comment]
@jessesquires what is our preferred location to put images?

My first inclination is to put them all inside `/img`, and name the files always including the issue? (e.g. `/img/vol-1-issue-1-header.jpg`), but I don't know what is customary with Jekyll.

**Comment by jessesquires** [comment]
@anaulin that's perfect 👌 

I wrote support for images, too. So we can actually use this front matter instead:

```jekyll
---
layout: post
title: ! 'Issue #N'
categories: [volume1]
image:
    file: null
    alt: null
    caption: null
    source_link: null
    half_width: false
---
```

Where:

- `file` = the filename only. (ex: `vol-1-issue-1-header.jpg`)
- `alt` = the `img` tag `alt` attribute
- `caption` = caption text to be displayed
- `source_link` = link to the original source of the image
- `half_width` = this is a layout setting. the image can expand to the full width of the container (`false`), or can be set to 50% of the container width (`true)`

Then, below `<!--excerpt-->` in the post, we'll need to add:

```jekyll
{% include post_image.html %}
```

---

I'll update the existing "fake" issues to use this so there's an example.

**Comment by anaulin** [comment]
So far I've only seen one image per legacy newsletter issue, and always for the header, so this should work great.

Thanks for the documentation and example snippets, @jessesquires , that's very helpful. 🙏🏼

**Comment by jessesquires** [comment]
Awesome. 

Yeah, I think having 1 header image per issue (or none) is best for Volume 2, also.

**Comment by jessesquires** [comment]
Just pushed a commit to add example images to the existing sample posts. Each has slightly different parameters in the front matter so you can see the differences.

should be available here once gh-pages builds it:
https://techworkersco.github.io/archive/

**Comment by jessesquires** [comment]
Finished adding categories! And updated the fake issues so there are examples.

@anaulin I ended up changing the front matter. Turns out it can actually be simpler with a single category. So we can use `category: Volume 1`.

And I wrote up some documentation for all this:
https://github.com/techworkersco/techworkersco.github.io/blob/master/.github/CONTRIBUTING.md

**Comment by anaulin** [comment]
@jessesquires the legacy posts don't seem to have an obvious "excerpt" for me to automagically use (e.g. see https://us11.campaign-archive.com/?u=194e57c175176cfd13007a197&id=a9d5f79101). If I simply skip the portion before `<!--excerpt-->`, will that work ok?

(After we import the content, I imagine we can go back and hand-tweak things further to make up "excerpts", if we want to.)

**Comment by anaulin** [comment]
Things seem to work ok if I don't have an explicit "excerpt" section, so I'm going with that for now.

**Comment by jessesquires** [comment]
@anaulin Ah, right.

It will work without an excerpt, but I think a good rule-of-thumb would be to just make the first paragraph the excerpt.

This text will show on the [archives page](https://techworkersco.github.io/archive/), but more importantly, that text is used to generate the "summary" for the RSS feed entries, and it is also used to generate the "blurbs" when sharing links on social media, like this for twitter:

<img width="574" alt="Screen Shot 2020-04-11 at 5 57 42 PM" src="https://user-images.githubusercontent.com/2301114/79058089-fab0ad80-7c1d-11ea-998c-61abd52fa3a1.png">

---

However, if that's difficult, I would say it's not a huge priority for the legacy issues.

**Comment by anaulin** [comment]
I can probably make the first paragraph into the excerpt, that's a good suggestion. I'll take a stab.

**Comment by anaulin** [comment]
PS Mailchimp archive HTML is like the ugliest HTML of the nineties, and I hate it. Thanks for listening!

**Comment by jessesquires** [comment]
> PS Mailchimp archive HTML is like the ugliest HTML of the nineties, and I hate it. Thanks for listening!

😆 Haha I'm sorry! 🙈

**Comment by anaulin** [comment]
Nah. Deep down, I find it fun. 👩‍🎤

**Comment by anaulin** [comment]
Ok, so I think I have the scraper working well enough that I can run it on the entire archive and then do any small remaining tweaks manually (since this is a one-time import, it will be faster to fix manually the remaining 1% of corner cases, than to get the code to 100% accuracy).

Before I do that, I'd like a double-check on the front matter and, in particular, what I'm using as the issue title.

Here is the beginning of the file I'm auto-generating right now for issue 20 of Volume 1 (https://us11.campaign-archive.com/?u=194e57c175176cfd13007a197&id=a9d5f79101):

filename: `_posts/2018-10-05-issue-20.md`
```
---
layout: post
title: ! 'So Too Shall We'
category: Volume 1
image:
    file: vol-1-issue-20-header.png
    alt: null
    caption: Tech Workers Coalition receives Working Partnerships USA 2018 Rise Up Solidarity Champion Award
    source_link: null
    half_width: false
---

On Wednesday, Tech Workers Coalition was recognized by Working Partnerships USA with a&nbsp;Solidarity Champion Award for organizing a movement inside the tech industry to demand transparency and justice for workers, immigrants, and communities affected by tech near and far. Read on for the full remarks from the courageous TWC volunteer who took the stage to accept the award:

<!--excerpt-->

{% include post_image.html %}

### Worker's Perspective

On Wednesday, Tech Workers Coalition was recognized by Working Partnerships USA with a&nbsp;Solidarity Champion Award for organizing a movement inside the tech industry to demand transparency and justice for workers, immigrants, and communities affected by tech near and far. Read on for the full remarks from the courageous TWC volunteer who took the stage to accept the award:  
  
_On behalf of the Tech Workers Coalition, I'd like to thank you for this solidarity award, and I'd like to thank everyone in attendance for partnering with Silicon Valley Rising and other WPUSA programs to help shape the Bay Area's relationship with labour._ 
[...]
```

You'll see that I'm using what the old newsletters use as "title". This is not consistent with us using "Issue N" as the title for Volume 2 titles. I could easily change that to use "Issue N", or a combination of title and issue number, or whatever else. Thoughts? Preferences?

And does the front matter and the excerpt section look ok, @jessesquires ?

**Comment by jessesquires** [comment]
@anaulin this is awesome! 🎉 nice work, everything looks perfect to me 💯 

> I could easily change that to use "Issue N", or a combination of title and issue number, or whatever else. Thoughts? Preferences?

I was going to say that I'm personally a fan of just having numbered issues, but given the new template we are considering, where we have a focus for each issue, I think number + title could be a better fit for us. I think my preference would be for that. I'm open to other ideas though.

If we combine issue number + title, I think it will look better without the `#` sign too.

```
title: 'Issue 20: So Too Shall We'
```

(also, I realized we don't need that leading `!` anymore for titles in the front matter -- that was only necessary for an older version of jekyll.)
