### ISSUE TITLE
Create an editorial vision/process doc

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#55]
Per our discussion during the May 5 meeting.

@stationaery I think you volunteered to do this, as well? If not feel free to re-assign, or we can discuss later.

#### Meeting notes

> Editorial process
>
> We need two separate docs:
> 1. editorial process, steps and schedule
> 1. editorial direction with a) political analysis on the industry without potential faux-pas, and b) commentary on our own efforts as a newsletter
>
> Host these docs in GH to enable conversation about them both

**Comment by stationaery** [comment]
Yep! @dellsystem are you interested in co-leading this with me? In particular, the editorial direction?

**Comment by stationaery** [comment]
@dellsystem and everyone, I revised our editorial direction doc to serve two purposes: 1) guidance for our newsletter collective, and also 2) potential points of alignment for our organizing in TWC. Please take it apart and put it back together however you want! See the doc here: https://docs.google.com/document/d/1iFHDLZxn8se0cLWNEQX5UV6ajrK-5a3w_X1MKiyNnic/edit#

We can migrate it to a GH checklist or even a page on the site, as soon as we think it's ready.

**Comment by jessesquires** [comment]
@techworkersco/newsletter-folks Assigning this task to everyone to take a look at the draft and sign-off. You can un-assign yourself once you've done that and comment here. 😄 

https://docs.google.com/document/d/1iFHDLZxn8se0cLWNEQX5UV6ajrK-5a3w_X1MKiyNnic/edit#

**Comment by jessesquires** [comment]
✅ Looks good to me. I left a few minor comments.

**Comment by anaulin** [comment]
Left a couple of very minor comments. Looks good to me otherwise. ✅

**Comment by dellsystem** [comment]
Left some comments and suggestions!
