### ISSUE TITLE
Fix mailchimp spam issue + custom domain email

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#75]
Reports that emails are going to spam because sender domain (`@protonmail`) is not owned by us.

Investigate getting an `@techworkersco` email address.

---

### DNS records

- Create a `CNAME` record for `k1._domainkey.techworkerscoalition.org` with value `dkim.mcsv.net`
- Create a `TXT` record with this value: `v=spf1 include:servers.mcsv.net ?all`
---

### Docs

The article below has information on what needs to be changed.  Set Up Custom Domain Authentication: DKIM and SPF: http://eepurl.com/b43Lqb  

If protonmail.com is not your domain (which it looks like it may be a free email service) then you may consider instead getting a custom domain to send from. The following two articles give a bit more context:

Limitations of Free Email Addresses: https://eepurl.com/dyil9c
Purchase a Domain in Mailchimp: https://eepurl.com/gtdfG5

**Comment by jessesquires** [comment]
This is now completed.

Emails will be sent from `news-noreply@techworkerscoalition.org`

**Comment by jessesquires** [comment]
@techworkersco/newsletter-folks This is now completed. 🎉 

Emails will be sent from `news-noreply@techworkerscoalition.org`. The domain is verified and authenticated.

This is a "no-reply" address to send from only. We will still use our proton mail account for everything else.

**Comment by anaulin** [comment]
Nice. Thanks for sorting this out, @jessesquires 😻

**Comment by stationaery** [comment]
HuzZah! Question: why not set up an alias to reply to the Protonmail
account?

**Comment by anaulin** [comment]
I can think of two reasons:
1) Administration and maintenance overhead.
2) It makes having an encrypted Protonmail account moot if we're forwarding email through other, presumably un-encrypted, services. 

That said, I don't know if we care about having an encrypted Protonmail account for this. In which case, if it was possible to set up a @techworkerscoalition.org account, that might be nicer than using the Protonmail one. Would require some more set up and relying on whoever runs techworkerscoalition.org to help administer it, though.

**Comment by stationaery** [comment]
1. is probably inevitable if we’re allowing emails in the first place :(

2. is a legitimate concern, not sure if we’re trying to ensure end to end
encryption, but why not, if we can

My reason for asking about reply ability is, I get a bit put off by seeing
no-reply emails, like I’m stuck on the receiving end of someone else’s
project. And I would like us to be able to include folks who care enough to
reply.

How do others feel about this?

**Comment by dellsystem** [comment]
thanks for sorting this @jessesquires!

I personally never pay attention to whether an email address is no-reply so I don't really mind that. The protonmail email is listed at the bottom of the email, right?

**Comment by jessesquires** [comment]
> The protonmail email is listed at the bottom of the email, right?

Correct. The "email us" link goes to proton mail.
