### ISSUE TITLE
MailChimp template tweaks

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#76]
Two proposed enhancements for the MailChimp template:
1) Move the “Read on the web »” link to the top/above the body text, because readers scrolling to the bottom will likely have read or skimmed the thing to their satisfaction already
2) Add the "Want to contribute? Email us or open a GitHub issue." copy/links to the bottom, to give readers an easier/quicker option to actually contribute

**Comment by jessesquires** [comment]
just fixed this.

## "read on the web" text

<img width="923" alt="Screen Shot 2020-05-23 at 12 43 13 PM" src="https://user-images.githubusercontent.com/2301114/82739287-4cefee80-9cf3-11ea-8e77-b6caac1bb109.png">

## footer text

<img width="931" alt="Screen Shot 2020-05-23 at 12 43 25 PM" src="https://user-images.githubusercontent.com/2301114/82739288-4d888500-9cf3-11ea-883e-43af57bb6e49.png">

**Comment by stationaery** [comment]
😊📧✨
