### ISSUE TITLE
Add some kind of link to "previous" or "archive" at the bottom of "latest" post in newsletter site main page

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#79]
When you land on https://news.techworkerscoalition.org/ you are shown the latest issue, and then if you read to the bottom it would be nice to show a link to previous issues, or the archive.

**Comment by stationaery** [comment]
Following on this- the current *Latest* label button on the landing page
seems superfluous. It’s also placed under the title instead above it like
the other nav buttons. And it is styled in bold dark font on a dark
background that demands attention. I click the button (or the issue title)
and then get taken to the same issue again but with the Previous button on
top, which seems awkward. Why did I click it? I feel silly. 🙃

Proposal: remove the “Latest” button

**Comment by stationaery** [comment]
Upon closer inspection (on desktop this time), I realize that the button is _not_ a link! I feel doubly silly now. 🙃🙃 But, it is still super dark/heavy compared to the article itself. 

So, new proposal: style the "Latest" button to look like the other nav buttons, and with a star, like "Latest 🌟" (another option, if you wish: "New 🌟")

Also, another proposal: at the bottom of the landing page, add the "Previous" nav button and social media sharing buttons.
