### ISSUE TITLE
Find a collaborative markdown editor?

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#81]
We are interested in using a collaborative markdown editor instead of Google Docs for drafting.

The goal is to reduce friction even more, as Google Docs is not great with markdown, but it is much easier to keep the draft in markdown so that transferring to GitHub is faster, easier, and less error-prone.

Potential options:
- https://hackmd.io
- quip: https://quip.com/blog/markdown

**Comment by jessesquires** [comment]
I'll try to investigate the options soon.

**Comment by anaulin** [comment]
The only one I've ever tried is https://draftin.com/, which is really nice (has built-in "diff" views) and stuff, but I am not sure if it there is a free account option.

**Comment by anaulin** [comment]
Ah, and Dropbox Paper is pretty nice, too, and it lets you export the markdown and also you can leave "comments" on the side, like in Google Docs: https://www.dropbox.com/paper

**Comment by stationaery** [comment]
PS! I've collaborated with folks using Paper to edit plain documents and
also print materials with complex layout. It's good!

**Comment by stationaery** [comment]
Paper worked out pretty well!
